### ISSUE TITLE
Binaries don't work

### ISSUE THREAD

**Issue by ShorterTuxedo** [SingularityT3/PseudoEngine2#1]
Hello,

The binaries you attached didn't work for my Windows computer, so I had to try it on a REPL.it.
Please try to fix the binaries, also add compile instructions for anyone to compile the program:

add `set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)` to CMakeLists.txt

then run 

```
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ PseudoEngine2
make
```

**Comment by SingularityT3** [comment]
They seem to be working on my machine. Could you please describe what happened when you launched the binary? Were there any errors that were shown?

**Comment by SingularityT3** [comment]
Its likely a linking issue and should be fixed now

**Comment by ShorterTuxedo** [comment]
Anyways this is a really great project, thanks for making it!
